services:
  frontend:
    build: .
    ports: 
      - "8080:8080"
  backend:
    build: ./Api/
    ports:
      - "8081:8082"
      - "8082:8082"
    environment:
      - ASPNETCORE_URLS=https://+:8082;http://+:8081
      - ASPNETCORE_Kestrel__Certificates__Development__Password=
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/Api.pfx
    volumes:
      - ~/.aspnet/https:/https:ro